// SPDX-License-Identifier: MIT OR Apache-2.0
// lockpick - Run every Rust quality gate in one command
// Copyright (c) 2026 Juan Luis Leal Contreras (Kuenlun)

#![cfg_attr(coverage_nightly, feature(coverage_attribute))]
#![cfg_attr(coverage_nightly, coverage(off))]

//! Side-effect contracts: `--fix` mutates source, the in-process
//! license-header gate flags offenders and skips `@generated` files,
//! signal-aware shutdown returns `128 + signum`, and a clean run keeps
//! stderr quiet with the summary on stdout.

mod common;

use common::{
    FORMATTED_MAIN_RS, TestResult, UNFORMATTED_MAIN_RS, dummy_cargo_project, run_lockpick,
    scratch_crate, stderr, stdout,
};

const SKIP_ALL_BUT_FMT: &[&str] = &[
    "--skip", "clippy", "--skip", "machete", "--skip", "audit", "--skip", "license", "--skip",
    "check", "--skip", "test", "--skip", "doc-test", "--skip", "doc",
];

#[test]
fn fix_flag_mutates_source_before_check() -> TestResult {
    let project = scratch_crate("fmt_fix", "", &[("src/main.rs", UNFORMATTED_MAIN_RS)]);
    let mut args: Vec<&str> = vec!["--fix"];
    args.extend_from_slice(SKIP_ALL_BUT_FMT);

    let out = run_lockpick(project.path()).args(&args).output()?;
    assert_eq!(
        out.status.code(),
        Some(0_i32),
        "expected exit 0 after --fix healed the tree, got code={code:?} stdout=\n{out_text}\nstderr=\n{err}",
        code = out.status.code(),
        out_text = stdout(&out),
        err = stderr(&out),
    );
    let body = std::fs::read_to_string(project.path().join("src/main.rs"))?;
    assert_eq!(
        body, FORMATTED_MAIN_RS,
        "src/main.rs should match the formatted baseline after --fix"
    );
    Ok(())
}

#[test]
fn pipeline_fails_without_fix_on_unformatted_source() -> TestResult {
    let project = scratch_crate("fmt_nofix", "", &[("src/main.rs", UNFORMATTED_MAIN_RS)]);
    let out = run_lockpick(project.path())
        .args(SKIP_ALL_BUT_FMT)
        .output()?;
    assert_eq!(
        out.status.code(),
        Some(1_i32),
        "expected exit 1 on unformatted source, got code={code:?} stdout=\n{out_text}",
        code = out.status.code(),
        out_text = stdout(&out),
    );
    let report = stdout(&out);
    assert!(report.contains("FAIL"), "missing FAIL marker:\n{report}");
    assert!(
        report.contains("fmt"),
        "summary should name the failing label `fmt`:\n{report}"
    );
    let body = std::fs::read_to_string(project.path().join("src/main.rs"))?;
    assert_eq!(
        body, UNFORMATTED_MAIN_RS,
        "src/main.rs must stay unchanged without --fix"
    );
    Ok(())
}

#[test]
fn license_header_detects_offender_and_skips_generated() -> TestResult {
    // Single test covering the three branches of the in-process gate:
    // a header-bearing file passes, a missing header fails with a
    // pointer at the offender, and a `@generated` file is silently
    // dropped from the scan even when its body lacks the header.
    const EXTRA_TOML: &str =
        "[package.metadata.lockpick]\nlicense-header = \"licenses/header.txt\"\n";
    const HEADER: &str = "// (c) Lockpick test\n";
    const HEADER_PATH: &str = "licenses/header.txt";

    struct Case<'a> {
        name: &'a str,
        files: Vec<(&'a str, &'a str)>,
        expected_code: i32,
        must_contain: &'a [&'a str],
    }

    // `println!` keeps clippy quiet (an empty `fn main` trips
    // `clippy::missing_const_for_fn`, which is denied in the fixture).
    const BODY: &str = "fn main() {\n    println!(\"hi\");\n}\n";
    let body_with_header = format!("{HEADER}\n{BODY}");
    let generated_body = format!("// @generated by build.rs\n\n{BODY}");

    let cases = [
        Case {
            name: "license_pass",
            files: vec![
                (HEADER_PATH, HEADER),
                ("src/main.rs", body_with_header.as_str()),
            ],
            expected_code: 0,
            must_contain: &["license", "PASS"],
        },
        Case {
            name: "license_fail",
            files: vec![(HEADER_PATH, HEADER), ("src/main.rs", BODY)],
            expected_code: 1,
            must_contain: &["files missing the expected license header:", "main.rs"],
        },
        Case {
            name: "license_generated",
            files: vec![
                (HEADER_PATH, HEADER),
                ("src/main.rs", body_with_header.as_str()),
                ("src/generated.rs", generated_body.as_str()),
            ],
            expected_code: 0,
            must_contain: &["file(s) checked against"],
        },
    ];

    for case in &cases {
        let project = scratch_crate(case.name, EXTRA_TOML, &case.files);
        // `-v` so the license PASS output (which carries the
        // `file(s) checked against` proof) lands on stdout, not just
        // the silent summary line.
        let out = run_lockpick(project.path())
            .args(["-v", "--skip", "machete", "--skip", "audit"])
            .output()?;
        let report = stdout(&out);
        assert_eq!(
            out.status.code(),
            Some(case.expected_code),
            "case `{name}`: expected exit {code}, got code={got:?} stdout=\n{report}",
            name = case.name,
            code = case.expected_code,
            got = out.status.code(),
        );
        for needle in case.must_contain {
            assert!(
                report.contains(needle),
                "case `{name}`: stdout missing `{needle}`:\n{report}",
                name = case.name,
            );
        }
    }
    Ok(())
}

#[test]
fn clean_run_keeps_stderr_quiet_and_summary_on_stdout() -> TestResult {
    let project = dummy_cargo_project();
    let out = run_lockpick(project.path())
        .args(["--skip", "machete", "--skip", "audit"])
        .output()?;
    let report = stdout(&out);
    let diag = stderr(&out);
    assert_eq!(
        out.status.code(),
        Some(0_i32),
        "expected exit 0 on clean run, got code={code:?} stdout=\n{report}\nstderr=\n{diag}",
        code = out.status.code(),
    );
    assert!(report.contains("OK:"), "missing success summary:\n{report}");
    assert!(
        diag.trim().is_empty(),
        "stderr must be empty on a clean run, got:\n{diag}"
    );
    Ok(())
}

#[test]
fn skip_coverage_without_config_notes_no_effect() -> TestResult {
    // Coverage is opt-in, so skipping it on an unconfigured project is
    // a no-op that must be called out instead of silently accepted.
    let project = dummy_cargo_project();
    let mut args: Vec<&str> = vec!["--skip", "coverage"];
    args.extend_from_slice(SKIP_ALL_BUT_FMT);

    let out = run_lockpick(project.path()).args(&args).output()?;
    assert_eq!(
        out.status.code(),
        Some(0_i32),
        "expected exit 0, got code={code:?} stderr=\n{err}",
        code = out.status.code(),
        err = stderr(&out),
    );
    assert!(
        stderr(&out).contains("--skip coverage has no effect"),
        "missing no-effect note on stderr:\n{err}",
        err = stderr(&out),
    );
    Ok(())
}

#[test]
fn skip_test_with_configured_coverage_notes_implied_skip() -> TestResult {
    // Coverage opts in via config, but `--skip test` starves the gate
    // of profraws, so lockpick must say it is implicitly skipped.
    let project = scratch_crate(
        "cov_skip_test",
        "[package.metadata.lockpick.coverage]\n",
        &[("src/main.rs", FORMATTED_MAIN_RS)],
    );

    let out = run_lockpick(project.path())
        .args(SKIP_ALL_BUT_FMT)
        .output()?;
    assert_eq!(
        out.status.code(),
        Some(0_i32),
        "expected exit 0, got code={code:?} stderr=\n{err}",
        code = out.status.code(),
        err = stderr(&out),
    );
    assert!(
        stderr(&out).contains("--skip test implies coverage will be skipped"),
        "missing implied-skip note on stderr:\n{err}",
        err = stderr(&out),
    );
    Ok(())
}

#[test]
fn license_scan_is_workspace_relative_and_includes_all_members() -> TestResult {
    let workspace = tempfile::tempdir()?;
    // Brackets exercise glob escaping in the workspace directory prefix.
    let root = workspace.path().join("workspace[1]");
    std::fs::create_dir_all(&root)?;
    std::fs::write(
        root.join("Cargo.toml"),
        "[workspace]\nmembers=[\"alpha\",\"beta\"]\nresolver=\"3\"\n[workspace.metadata.lockpick]\nlicense-header=\"header.txt\"\n",
    )?;
    std::fs::write(root.join("header.txt"), "// license\n")?;
    for name in ["alpha", "beta"] {
        let member = root.join(name);
        std::fs::create_dir_all(member.join("src"))?;
        std::fs::write(
            member.join("Cargo.toml"),
            common::cargo_toml_strict(name, ""),
        )?;
        std::fs::write(
            member.join("src/lib.rs"),
            "// license\npub const VALUE: u8 = 1;\n",
        )?;
    }
    let run = |cwd: &std::path::Path| {
        run_lockpick(cwd)
            .args([
                "--skip",
                "check,clippy,fmt,test,doc,doc-test,machete,audit",
                "-v",
            ])
            .output()
    };
    for cwd in [&root, &root.join("alpha/src")] {
        let out = run(cwd)?;
        assert_eq!(out.status.code(), Some(0_i32), "{}", common::combined(&out));
        assert!(stdout(&out).contains("2 file(s) checked"));
    }
    std::fs::write(root.join("beta/src/lib.rs"), "pub const VALUE: u8 = 1;\n")?;
    let out = run(&root.join("alpha"))?;
    assert_eq!(out.status.code(), Some(1_i32), "{}", common::combined(&out));
    assert!(stdout(&out).contains("beta"));
    Ok(())
}

#[test]
fn license_scan_rejects_invalid_empty_and_unmatched_globs() -> TestResult {
    for pattern in ["[", "missing/**/*.rs", ""] {
        let extra = format!(
            "[package.metadata.lockpick]\nlicense-header=\"header.txt\"\nlicense-header-globs=[{pattern:?}]\n"
        );
        let project = scratch_crate(
            "bad_globs",
            &extra,
            &[
                ("src/main.rs", FORMATTED_MAIN_RS),
                ("header.txt", "// license\n"),
            ],
        );
        let out = run_lockpick(project.path())
            .args(["--skip", "check,clippy,fmt,test,doc,doc-test,machete,audit"])
            .output()?;
        assert_eq!(out.status.code(), Some(1_i32), "{}", common::combined(&out));
        assert!(stdout(&out).contains("license-header-globs"));
    }
    Ok(())
}

#[test]
fn license_scan_requires_each_explicit_glob_to_match_files() -> TestResult {
    for (patterns, unmatched) in [
        ("[\"src/**/*.rs\", \"test/**/*.rs\"]", Some("test/**/*.rs")),
        ("[\"src/**/*.rs\", \"tests\"]", Some("tests")),
        ("[\"src/**/*.rs\", \"src/main.rs\"]", None),
    ] {
        let extra = format!(
            "[package.metadata.lockpick]\nlicense-header=\"header.txt\"\nlicense-header-globs={patterns}\n"
        );
        let project = scratch_crate(
            "mixed_globs",
            &extra,
            &[
                ("src/main.rs", "// license\nfn main() {}\n"),
                ("header.txt", "// license\n"),
            ],
        );
        std::fs::create_dir(project.path().join("tests"))?;
        let out = run_lockpick(project.path())
            .args([
                "--skip",
                "check,clippy,fmt,test,doc,doc-test,machete,audit",
                "-v",
            ])
            .output()?;
        let report = stdout(&out);
        if let Some(pattern) = unmatched {
            assert_eq!(out.status.code(), Some(1_i32), "{}", common::combined(&out));
            assert!(report.contains("matched no source files"), "{report}");
            assert!(report.contains(pattern), "{report}");
        } else {
            assert_eq!(out.status.code(), Some(0_i32), "{}", common::combined(&out));
            assert!(report.contains("1 file(s) checked"), "{report}");
        }
    }
    Ok(())
}

#[test]
fn failed_fix_stops_before_the_check_pipeline() -> TestResult {
    let project = scratch_crate("failed_fix", "", &[("src/main.rs", common::BROKEN_MAIN_RS)]);
    let out = run_lockpick(project.path())
        .args(["--fix", "--skip", "machete,audit"])
        .output()?;
    assert_eq!(out.status.code(), Some(1_i32), "{}", common::combined(&out));
    assert!(stderr(&out).contains("fix: cargo clippy exited with non-zero status"));
    assert!(!stdout(&out).contains("checks passed"));
    Ok(())
}
