// SPDX-License-Identifier: MIT OR Apache-2.0
// lockpick - Run every Rust quality gate in one command
// Copyright (c) 2026 Juan Luis Leal Contreras (Kuenlun)

#![cfg_attr(coverage_nightly, feature(coverage_attribute))]
#![cfg_attr(coverage_nightly, coverage(off))]
#![allow(clippy::unwrap_used)]

//! Side-effect contracts: `--fix` mutates source, the in-process
//! license-header gate flags offenders and skips `@generated` files,
//! signal-aware shutdown returns `128 + signum`, and a clean run keeps
//! stderr quiet with the summary on stdout.

mod common;

use common::{
    FORMATTED_MAIN_RS, TestResult, UNFORMATTED_MAIN_RS, dummy_cargo_project, run_lockpick,
    scratch_crate, stderr, stdout,
};

const SKIP_ALL_BUT_FMT: &[&str] = &[
    "--skip", "clippy", "--skip", "machete", "--skip", "audit", "--skip", "coverage", "--skip",
    "license", "--skip", "check", "--skip", "test", "--skip", "doc-test", "--skip", "doc",
];

#[test]
fn fix_flag_mutates_source_before_check() -> TestResult {
    let project = scratch_crate("fmt_fix", "", &[("src/main.rs", UNFORMATTED_MAIN_RS)]);
    let mut args: Vec<&str> = vec!["--fix"];
    args.extend_from_slice(SKIP_ALL_BUT_FMT);

    let out = run_lockpick(project.path()).args(&args).output()?;
    assert_eq!(
        out.status.code(),
        Some(0),
        "expected exit 0 after --fix healed the tree, got code={code:?} stdout=\n{out_text}\nstderr=\n{err}",
        code = out.status.code(),
        out_text = stdout(&out),
        err = stderr(&out),
    );
    let body = std::fs::read_to_string(project.path().join("src/main.rs"))?;
    assert_eq!(
        body, FORMATTED_MAIN_RS,
        "src/main.rs should match the formatted baseline after --fix"
    );
    Ok(())
}

#[test]
fn pipeline_fails_without_fix_on_unformatted_source() -> TestResult {
    let project = scratch_crate("fmt_nofix", "", &[("src/main.rs", UNFORMATTED_MAIN_RS)]);
    let out = run_lockpick(project.path())
        .args(SKIP_ALL_BUT_FMT)
        .output()?;
    assert_eq!(
        out.status.code(),
        Some(1),
        "expected exit 1 on unformatted source, got code={code:?} stdout=\n{out_text}",
        code = out.status.code(),
        out_text = stdout(&out),
    );
    let report = stdout(&out);
    assert!(report.contains("FAIL"), "missing FAIL marker:\n{report}");
    assert!(
        report.contains("fmt"),
        "summary should name the failing label `fmt`:\n{report}"
    );
    let body = std::fs::read_to_string(project.path().join("src/main.rs"))?;
    assert_eq!(
        body, UNFORMATTED_MAIN_RS,
        "src/main.rs must stay unchanged without --fix"
    );
    Ok(())
}

#[test]
fn license_header_detects_offender_and_skips_generated() -> TestResult {
    // Single test covering the three branches of the in-process gate:
    // a header-bearing file passes, a missing header fails with a
    // pointer at the offender, and a `@generated` file is silently
    // dropped from the scan even when its body lacks the header.
    const EXTRA_TOML: &str =
        "[package.metadata.lockpick]\nlicense-header = \"licenses/header.txt\"\n";
    const HEADER: &str = "// (c) Lockpick test\n";
    const HEADER_PATH: &str = "licenses/header.txt";

    struct Case<'a> {
        name: &'a str,
        files: Vec<(&'a str, &'a str)>,
        expected_code: i32,
        must_contain: &'a [&'a str],
    }

    // `println!` keeps clippy quiet (an empty `fn main` trips
    // `clippy::missing_const_for_fn`, which is denied in the fixture).
    const BODY: &str = "fn main() {\n    println!(\"hi\");\n}\n";
    let body_with_header = format!("{HEADER}\n{BODY}");
    let generated_body = format!("// @generated by build.rs\n\n{BODY}");

    let cases = [
        Case {
            name: "license_pass",
            files: vec![
                (HEADER_PATH, HEADER),
                ("src/main.rs", body_with_header.as_str()),
            ],
            expected_code: 0,
            must_contain: &["license", "PASS"],
        },
        Case {
            name: "license_fail",
            files: vec![(HEADER_PATH, HEADER), ("src/main.rs", BODY)],
            expected_code: 1,
            must_contain: &["files missing the expected license header:", "main.rs"],
        },
        Case {
            name: "license_generated",
            files: vec![
                (HEADER_PATH, HEADER),
                ("src/main.rs", body_with_header.as_str()),
                ("src/generated.rs", generated_body.as_str()),
            ],
            expected_code: 0,
            must_contain: &["file(s) checked against"],
        },
    ];

    for case in &cases {
        let project = scratch_crate(case.name, EXTRA_TOML, &case.files);
        // `-v` so the license PASS output (which carries the
        // `file(s) checked against` proof) lands on stdout, not just
        // the silent summary line.
        let out = run_lockpick(project.path())
            .args([
                "-v", "--skip", "coverage", "--skip", "machete", "--skip", "audit",
            ])
            .output()?;
        let report = stdout(&out);
        assert_eq!(
            out.status.code(),
            Some(case.expected_code),
            "case `{name}`: expected exit {code}, got code={got:?} stdout=\n{report}",
            name = case.name,
            code = case.expected_code,
            got = out.status.code(),
        );
        for needle in case.must_contain {
            assert!(
                report.contains(needle),
                "case `{name}`: stdout missing `{needle}`:\n{report}",
                name = case.name,
            );
        }
    }
    Ok(())
}

#[cfg(unix)]
#[test]
fn signal_aware_exit_uses_128_plus_signum() -> TestResult {
    // Forward SIGTERM mid-pipeline and assert lockpick exits 143
    // (128 + 15). Stdout/stderr go to `/dev/null` because the
    // signal-aware exit path is what we test, not the captured output.
    use std::process::Stdio;
    use std::thread;
    use std::time::Duration;

    let project = dummy_cargo_project();
    let mut child = run_lockpick(project.path())
        .args(["--skip", "coverage", "--skip", "machete", "--skip", "audit"])
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .spawn()?;

    // Give cargo time to spawn at least one child so the SIGTERM hits
    // the handler with live PIDs to forward to.
    thread::sleep(Duration::from_millis(300));
    let kill = std::process::Command::new("kill")
        .args(["-TERM", &child.id().to_string()])
        .status()?;
    assert!(kill.success(), "kill -TERM lockpick failed");

    let status = child.wait()?;
    assert_eq!(
        status.code(),
        Some(143),
        "expected exit 143 (128 + SIGTERM), got code={code:?}",
        code = status.code(),
    );
    Ok(())
}

#[test]
fn clean_run_keeps_stderr_quiet_and_summary_on_stdout() -> TestResult {
    let project = dummy_cargo_project();
    let out = run_lockpick(project.path())
        .args(["--skip", "coverage", "--skip", "machete", "--skip", "audit"])
        .output()?;
    let report = stdout(&out);
    let diag = stderr(&out);
    assert_eq!(
        out.status.code(),
        Some(0),
        "expected exit 0 on clean run, got code={code:?} stdout=\n{report}\nstderr=\n{diag}",
        code = out.status.code(),
    );
    assert!(report.contains("OK:"), "missing success summary:\n{report}");
    assert!(
        diag.trim().is_empty(),
        "stderr must be empty on a clean run, got:\n{diag}"
    );
    Ok(())
}
