// SPDX-License-Identifier: MIT OR Apache-2.0
// lockpick - Rust CLI to enforce merge checks and code quality
// Copyright (c) 2026 Juan Luis Leal Contreras (Kuenlun)

//! License-header check. Verifies that every file matched by the
//! configured globs starts with the bytes of a canonical header file.
//! Files whose first line contains `@generated` are skipped.
//!
//! Opt-in: only runs when `[*.metadata.lockpick] license-header = "..."`
//! is set in `Cargo.toml`.

use std::fs;
use std::path::PathBuf;

use super::Check;
use crate::reporter::{CheckOutcome, TaskStatus};

pub struct LicenseHeaderCheck {
    pub header_path: PathBuf,
    pub globs: Vec<String>,
}

#[must_use]
pub fn default_globs() -> Vec<String> {
    vec![
        "src/**/*.rs".to_string(),
        "tests/**/*.rs".to_string(),
        "examples/**/*.rs".to_string(),
        "benches/**/*.rs".to_string(),
    ]
}

impl Check for LicenseHeaderCheck {
    fn label(&self) -> &'static str {
        "license"
    }

    fn cmd(&self) -> String {
        format!("license-header against `{}`", self.header_path.display())
    }

    fn run(&self) -> CheckOutcome {
        let header = match fs::read(&self.header_path) {
            Ok(bytes) => bytes,
            Err(e) => {
                return CheckOutcome {
                    status: TaskStatus::Fail,
                    output: format!(
                        "could not read license header file `{}`: {e}",
                        self.header_path.display()
                    ),
                };
            }
        };
        if header.is_empty() {
            return CheckOutcome {
                status: TaskStatus::Fail,
                output: format!(
                    "license header file `{}` is empty",
                    self.header_path.display()
                ),
            };
        }

        let files = match collect_files(&self.globs) {
            Ok(f) => f,
            Err(e) => {
                return CheckOutcome {
                    status: TaskStatus::Fail,
                    output: format!("invalid glob in license-header-globs: {e}"),
                };
            }
        };

        let mut offenders: Vec<PathBuf> = Vec::new();
        let mut scanned = 0_usize;
        for file in files {
            if file == self.header_path {
                continue;
            }
            let Ok(contents) = fs::read(&file) else {
                offenders.push(file);
                continue;
            };
            if is_generated(&contents) {
                continue;
            }
            scanned += 1;
            if !contents.starts_with(&header) {
                offenders.push(file);
            }
        }

        if offenders.is_empty() {
            return CheckOutcome {
                status: TaskStatus::Pass,
                output: format!(
                    "{scanned} file(s) checked against `{}`",
                    self.header_path.display()
                ),
            };
        }

        let mut lines: Vec<String> = vec!["files missing the expected license header:".to_string()];
        for path in &offenders {
            lines.push(format!("  - {}", path.display()));
        }
        lines.push(String::new());
        lines.push(format!(
            "expected header (from `{}`):",
            self.header_path.display()
        ));
        for line in String::from_utf8_lossy(&header).lines() {
            lines.push(format!("  | {line}"));
        }
        CheckOutcome {
            status: TaskStatus::Fail,
            output: lines.join("\n"),
        }
    }
}

fn collect_files(patterns: &[String]) -> Result<Vec<PathBuf>, glob::PatternError> {
    let mut files = Vec::new();
    for pattern in patterns {
        for entry in glob::glob(pattern)? {
            if let Ok(path) = entry
                && path.is_file()
            {
                files.push(path);
            }
        }
    }
    Ok(files)
}

fn is_generated(contents: &[u8]) -> bool {
    let first_line = contents.split(|&b| b == b'\n').next().unwrap_or(b"");
    let line = String::from_utf8_lossy(first_line);
    line.contains("@generated")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn detects_generated_marker_on_first_line() {
        assert!(is_generated(b"// @generated by prost\nfn foo() {}"));
        assert!(is_generated(b"//! @generated\n"));
        assert!(!is_generated(
            b"// SPDX-License-Identifier: MIT\n@generated"
        ));
    }

    #[test]
    fn default_globs_cover_canonical_layout() {
        let g = default_globs();
        assert_eq!(g.len(), 4);
        assert!(g.iter().any(|p| p == "src/**/*.rs"));
        assert!(g.iter().any(|p| p == "tests/**/*.rs"));
        assert!(g.iter().any(|p| p == "examples/**/*.rs"));
        assert!(g.iter().any(|p| p == "benches/**/*.rs"));
    }

    #[test]
    fn unconfigured_label_is_license() {
        let check = LicenseHeaderCheck {
            header_path: PathBuf::from("/nonexistent"),
            globs: vec![],
        };
        assert_eq!(check.label(), "license");
    }

    #[test]
    fn cmd_describes_the_header_being_enforced() {
        let check = LicenseHeaderCheck {
            header_path: PathBuf::from(".github/license_header.rs"),
            globs: vec![],
        };
        assert!(check.cmd().contains(".github/license_header.rs"));
    }

    #[test]
    fn run_fails_when_header_file_is_missing() {
        let check = LicenseHeaderCheck {
            header_path: PathBuf::from("/definitely/does/not/exist.txt"),
            globs: vec![],
        };
        let outcome = check.run();
        assert!(outcome.failed());
        assert!(outcome.output.contains("could not read"));
    }

    #[test]
    fn run_fails_when_header_file_is_empty() {
        let dir = std::env::temp_dir().join(format!("lockpick_empty_{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let header = dir.join("h.txt");
        std::fs::write(&header, b"").unwrap();
        let check = LicenseHeaderCheck {
            header_path: header,
            globs: vec![],
        };
        let outcome = check.run();
        assert!(outcome.failed());
        assert!(outcome.output.contains("empty"));
        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn run_fails_on_bad_glob_pattern() {
        let dir = std::env::temp_dir().join(format!("lockpick_badglob_{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let header = dir.join("h.txt");
        std::fs::write(&header, b"// HEADER\n").unwrap();
        let check = LicenseHeaderCheck {
            header_path: header,
            globs: vec!["a/***/b".to_string()], // invalid glob
        };
        let outcome = check.run();
        assert!(outcome.failed());
        assert!(outcome.output.to_lowercase().contains("glob"));
        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn run_passes_when_every_scanned_file_starts_with_header() {
        let dir = std::env::temp_dir().join(format!("lockpick_ok_{}", std::process::id()));
        std::fs::create_dir_all(dir.join("src")).unwrap();
        let header = dir.join("h.txt");
        std::fs::write(&header, b"// HEADER\n").unwrap();
        std::fs::write(dir.join("src").join("a.rs"), b"// HEADER\nfn main() {}\n").unwrap();
        std::fs::write(dir.join("src").join("b.rs"), b"// HEADER\nfn other() {}\n").unwrap();
        let check = LicenseHeaderCheck {
            header_path: header,
            globs: vec![format!("{}/src/*.rs", dir.display())],
        };
        let outcome = check.run();
        assert!(outcome.passed(), "got: {}", outcome.output);
        assert!(outcome.output.contains("2 file(s) checked"));
        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn run_lists_offenders_with_paths() {
        let dir = std::env::temp_dir().join(format!("lockpick_bad_{}", std::process::id()));
        std::fs::create_dir_all(dir.join("src")).unwrap();
        let header = dir.join("h.txt");
        std::fs::write(&header, b"// HEADER\n").unwrap();
        // One good, one missing the header:
        std::fs::write(dir.join("src").join("ok.rs"), b"// HEADER\nfn ok() {}\n").unwrap();
        std::fs::write(dir.join("src").join("bad.rs"), b"fn bad() {}\n").unwrap();
        let check = LicenseHeaderCheck {
            header_path: header,
            globs: vec![format!("{}/src/*.rs", dir.display())],
        };
        let outcome = check.run();
        assert!(outcome.failed());
        assert!(outcome.output.contains("bad.rs"));
        assert!(outcome.output.contains("expected header"));
        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn run_skips_generated_files() {
        let dir = std::env::temp_dir().join(format!("lockpick_gen_{}", std::process::id()));
        std::fs::create_dir_all(dir.join("src")).unwrap();
        let header = dir.join("h.txt");
        std::fs::write(&header, b"// HEADER\n").unwrap();
        std::fs::write(dir.join("src").join("real.rs"), b"// HEADER\nfn x() {}\n").unwrap();
        // This file has NO header but is marked @generated, so it should be skipped.
        std::fs::write(
            dir.join("src").join("gen.rs"),
            b"// @generated by prost\nfn g() {}\n",
        )
        .unwrap();
        let check = LicenseHeaderCheck {
            header_path: header,
            globs: vec![format!("{}/src/*.rs", dir.display())],
        };
        let outcome = check.run();
        assert!(outcome.passed(), "got: {}", outcome.output);
        // Only one file was actually scanned (the other was skipped).
        assert!(outcome.output.contains("1 file(s) checked"));
        std::fs::remove_dir_all(&dir).ok();
    }
}
